<template>
<v-container>
  <v-row 
  justify="center"
  ><h2>Compétences</h2></v-row>
  <v-divider></v-divider>
  <v-divider></v-divider>
  <v-row>


    <v-col>
  <v-card
    class="mx-auto"
    max-width="336"
  >
    <v-card-title>Languages</v-card-title>

    <v-card-text>
      <p>Html</p>
      <v-progress-linear
        color="black"
        height="10"
        value="80"
        stream
        buffer-value='0'
        striped
      ></v-progress-linear>
      <br>
      <p>CSS</p>
      <v-progress-linear
        color="red"
        height="10"
        value="70"
        stream
        buffer-value='0'
        striped
      ></v-progress-linear>
      <br>
      <p>PHP</p>
      <v-progress-linear
        height="10"
        value="80"
        striped
        stream
        buffer-value='0'
        color="black"
      ></v-progress-linear>
      <br>
      <p>SQL</p>
      <v-progress-linear
        value="60"
        height="10"
        striped
        stream
        buffer-value='0'
        color="red"
      ></v-progress-linear>
      <br>
          <p>JavaScript</p>
      <v-progress-linear
        color="black"
        height="10"
        value="50"
        striped
        stream
        buffer-value='0'
      ></v-progress-linear>
      <br> 
    </v-card-text>
  </v-card>
  </v-col>
  <v-col>
  <v-card
    class="mx-auto"
    max-width="336"
  >
    <v-card-title>FrameWorks</v-card-title>

    <v-card-text>
      <p>Bootstrap</p>
      <v-progress-linear
        color="black"
        height="10"
        value="85"
        striped
        stream
        buffer-value='0'
      ></v-progress-linear>
      <br>
      <p>VueJS</p>
      <v-progress-linear
        color="red"
        height="10"
        value="20"
        striped
        stream
        buffer-value='0'
      ></v-progress-linear>
      <br>
      <p>CodeIgniter</p>
      <v-progress-linear
        height="10"
        value="60"
        striped
        color="black"
        stream
        buffer-value='0'
      ></v-progress-linear>
      <br>
      <p>Vuetify</p>
      <v-progress-linear
        value="40"
        height="10"
        striped
        color="red"
        stream
        buffer-value='0'
      ></v-progress-linear>
      <br>
    </v-card-text>
  </v-card>
  </v-col>
  </v-row>
  </v-container>
</template>

